version: '3.8'

services:
  postgres_db: 
    image: postgres:15 
    container_name: pix_db_container 
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}  
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin123} 
      POSTGRES_DB: ${POSTGRES_DB:-pix_db} 
    ports:
      - "${POSTGRES_PORT:-4321}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
    restart: unless-stopped 

volumes:
  pgdata: