services:
  postgres_db: 
    image: postgres:15 
    container_name: pix_db_container 
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}  
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin123} 
      POSTGRES_DB: ${POSTGRES_DB:-pix_db} 
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
    restart: unless-stopped 
  api:
    container_name: pix_api_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-3000}
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - postgres_db
    restart: unless-stopped



volumes:
  pgdata: